"""create open finance connection table

Revision ID: 4a442c9258ee
Revises: f7b0884c0c6d
Create Date: 2026-06-12 23:59:07.659025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a442c9258ee'
down_revision: Union[str, Sequence[str], None] = 'f7b0884c0c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_finance_connection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pluggy_connection_id', sa.String(), nullable=False),
    sa.Column('institution_image_url', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CONECTADO', 'ERRO_LOGIN', 'ATUALIZANDO', 'EXPIRADO', name='connectionstatus'), nullable=False),
    sa.Column('consent_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_finance_connection')
    # ### end Alembic commands ###
