"""add relationship with user table to transaction table

Revision ID: ed5f90b45285
Revises: 859b9bd40a77
Create Date: 2026-06-14 22:33:16.808761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5f90b45285'
down_revision: Union[str, Sequence[str], None] = '859b9bd40a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('transaction_user_id_fkey'), 'transaction', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_user_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    # ### end Alembic commands ###
