"""update column type of date  in transactions for ddatetime

Revision ID: f0c5ddd1d904
Revises: e36dcd2264b7
Create Date: 2026-06-13 16:39:19.317678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0c5ddd1d904'
down_revision: Union[str, Sequence[str], None] = 'e36dcd2264b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'date', type_=sa.DateTime())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'date', type_=sa.Date())
    # ### end Alembic commands ###
